config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :friend_requests

      resources :likes

      resources :comments

      resources :poets

      resources :poems
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "poems#index"
  resources :friend_requests
  resources :likes
  resources :comments
  resources :poets
  resources :poems
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/poet.rb
class Poet < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  # Direct associations

  has_many   :received_friend_requests,
             class_name: "FriendRequest",
             foreign_key: "recipient_id",
             dependent: :destroy

  has_many   :sent_friend_requests,
             class_name: "FriendRequest",
             foreign_key: "sender_id",
             dependent: :destroy

  has_many   :likes,
             foreign_key: "liker_id",
             dependent: :destroy

  has_many   :comments,
             foreign_key: "commenter_id",
             dependent: :destroy

  has_many   :poems,
             foreign_key: "author_id",
             dependent: :destroy

  # Indirect associations

  has_many   :liked_poems,
             through: :likes,
             source: :poem

  has_many   :senders,
             through: :received_friend_requests,
             source: :sender

  has_many   :recipients,
             through: :sent_friend_requests,
             source: :recipient

  # Validations

  # Scopes

  def to_s
    email
  end
end

app/controllers/api/v1/poets_controller.rb
class Api::V1::PoetsController < Api::V1::GraphitiController
  def index
    poets = PoetResource.all(params)
    respond_with(poets)
  end

  def show
    poet = PoetResource.find(params)
    respond_with(poet)
  end

  def create
    poet = PoetResource.build(params)

    if poet.save
      render jsonapi: poet, status: :created
    else
      render jsonapi_errors: poet
    end
  end

  def update
    poet = PoetResource.find(params)

    if poet.update_attributes
      render jsonapi: poet
    else
      render jsonapi_errors: poet
    end
  end

  def destroy
    poet = PoetResource.find(params)

    if poet.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: poet
    end
  end
end

app/controllers/poets_controller.rb
class PoetsController < ApplicationController
  before_action :set_poet, only: %i[show edit update destroy]

  def index
    @q = Poet.ransack(params[:q])
    @poets = @q.result(distinct: true).includes(:poems, :comments, :likes,
                                                :sent_friend_requests, :received_friend_requests, :recipients, :senders, :liked_poems).page(params[:page]).per(10)
  end

  def show
    @friend_request = FriendRequest.new
    @like = Like.new
    @comment = Comment.new
    @poem = Poem.new
  end

  def new
    @poet = Poet.new
  end

  def edit; end

  def create
    @poet = Poet.new(poet_params)

    if @poet.save
      redirect_to @poet, notice: "Poet was successfully created."
    else
      render :new
    end
  end

  def update
    if @poet.update(poet_params)
      redirect_to @poet, notice: "Poet was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @poet.destroy
    redirect_to poets_url, notice: "Poet was successfully destroyed."
  end

  private

  def set_poet
    @poet = Poet.find(params[:id])
  end

  def poet_params
    params.require(:poet).permit(:email, :password, :name, :bio, :dob, :photo)
  end
end

app/views/poets/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Poet #<%= poet.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Email</dt>
      <dd><%= poet.email %></dd>

      <dt>Password</dt>
      <dd><%= poet.password %></dd>

      <dt>Name</dt>
      <dd><%= poet.name %></dd>

      <dt>Bio</dt>
      <dd><%= poet.bio %></dd>

      <dt>Dob</dt>
      <dd><%= poet.dob %></dd>

      <dt>Photo</dt>
      <dd>
        <%= cl_image_tag @poet.photo, class: "img-fluid" %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back poet, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_poet_url(poet), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to poet, method: :delete, data: { confirm: "Do you really want to delete this poet?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(poet.updated_at) %> ago
  </div>
</div>

app/views/poets/_poet_comments_new_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :body %>

    <%= f.text_field :body, class: "form-control" %>
  </div>

  <%= f.hidden_field :commenter_id, value: @poet.id %>

  <div class="form-group">
    <%= f.label :poem_id %>

    <%= f.collection_select :poem_id, Poem.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create comment", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/poets/_poet_likes.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Likes

    <a data-toggle="collapse" href="#poet_likes_new_form">
      Add like
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @poet.likes.each do |like| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to like, like %>

        <%= link_to like, method: :delete, data: { confirm: "Do you really want to delete this like" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="poet_likes_new_form">
        <%= render partial: "poets/poet_likes_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/poets/_poet_likes_new_form.html.erb
<%= form_with(model: @like, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :poem_id %>

    <%= f.collection_select :poem_id, Poem.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :liker_id, value: @poet.id %>

  <%= f.submit "Create like", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/poets/_poet_poems.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Poems

    <a data-toggle="collapse" href="#poet_poems_new_form">
      Add poem
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @poet.poems.each do |poem| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to poem, poem %>

        <%= link_to poem, method: :delete, data: { confirm: "Do you really want to delete this poem" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="poet_poems_new_form">
        <%= render partial: "poets/poet_poems_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/poets/_poet_poems_new_form.html.erb
<%= form_with(model: @poem, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :title %>

    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>

    <%= f.text_field :body, class: "form-control" %>
  </div>

  <%= f.hidden_field :author_id, value: @poet.id %>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.datetime_select :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :commentary %>

    <%= f.text_field :commentary, class: "form-control" %>
  </div>

  <%= f.submit "Create poem", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/poets/_poet_received_friend_requests.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Received Friend Requests

    <a data-toggle="collapse" href="#poet_received_friend_requests_new_form">
      Add friend request
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @poet.received_friend_requests.each do |friend_request| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to friend_request, friend_request %>

        <%= link_to friend_request, method: :delete, data: { confirm: "Do you really want to delete this friend_request" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="poet_received_friend_requests_new_form">
        <%= render partial: "poets/poet_received_friend_requests_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/poets/_poet_received_friend_requests_new_form.html.erb
<%= form_with(model: @friend_request, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :sender_id %>

    <%= f.text_field :sender_id, class: "form-control" %>
  </div>

  <%= f.hidden_field :recipient_id, value: @poet.id %>

  <%= f.submit "Create friend request", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/poets/_poet_sent_friend_requests.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Sent Friend Requests

    <a data-toggle="collapse" href="#poet_sent_friend_requests_new_form">
      Add friend request
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @poet.sent_friend_requests.each do |friend_request| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to friend_request, friend_request %>

        <%= link_to friend_request, method: :delete, data: { confirm: "Do you really want to delete this friend_request" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="poet_sent_friend_requests_new_form">
        <%= render partial: "poets/poet_sent_friend_requests_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/poets/_poet_sent_friend_requests_new_form.html.erb
<%= form_with(model: @friend_request, local: true) do |f| %>

  <%= f.hidden_field :sender_id, value: @poet.id %>

  <div class="form-group">
    <%= f.label :recipient_id %>

    <%= f.text_field :recipient_id, class: "form-control" %>
  </div>

  <%= f.submit "Create friend request", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/poets/_poets_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "poets_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :email_cont, "Email contains" %>
    <%= f.text_field :email_cont, :class => "form-control", :placeholder => "Email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :dob, "Dob" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='dobgteqPicker' data-target-input="nearest">
          <%= f.text_field :dob_gteq, :class => "form-control datetimepicker-input", :placeholder => "Dob greater than or equal to", :data => {:target => '#dobgteqPicker'} %>
          <div class="input-group-append" data-target='#dobgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='doblteqPicker' data-target-input="nearest">
          <%= f.text_field :dob_lteq, :class => "form-control datetimepicker-input", :placeholder => "Dob less than or equal to", :data => {:target => '#doblteqPicker'} %>
          <div class="input-group-append" data-target='#doblteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#dobgteqPicker').datetimepicker({
              format: 'MM/DD/YYYY'
          });
          $('#doblteqPicker').datetimepicker({
              useCurrent: false,
              format: 'MM/DD/YYYY'
          });
          $('#dobgteqPicker').on("dp.change", function (e) {
              $('#doblteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#doblteqPicker').on("dp.change", function (e) {
              $('#dobgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :bio_cont, "Bio contains" %>
    <%= f.text_field :bio_cont, :class => "form-control", :placeholder => "Bio contains" %>
  </div>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :poems_title_cont, "Poems title contains" %>
    <%= f.text_field :poems_title_cont, :class => "form-control", :placeholder => "Poems title contains" %>
  </div>

  <div class="form-group">
    <%= f.label :comments_body_cont, "Comments body contains" %>
    <%= f.text_field :comments_body_cont, :class => "form-control", :placeholder => "Comments body contains" %>
  </div>

  <div class="form-group">
    <%= f.label :recipients_email_cont, "Recipients email contains" %>
    <%= f.text_field :recipients_email_cont, :class => "form-control", :placeholder => "Recipients email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :senders_email_cont, "Senders email contains" %>
    <%= f.text_field :senders_email_cont, :class => "form-control", :placeholder => "Senders email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :liked_poems_title_cont, "Liked poems title contains" %>
    <%= f.text_field :liked_poems_title_cont, :class => "form-control", :placeholder => "Liked poems title contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/poets" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#poets_filters">
  Show filters
</a>

app/views/poets/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Poet #<%= @poet.id %>
      </h2>

      <div class="card-body">
        <%= render "form", poet: @poet %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/poets/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Poets

      <%= link_to new_poet_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "poets/poets_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Poets

        <%= link_to new_poet_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @poets, partial: "list_item", as: :poet %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @poets, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/poets/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Poet
      </h2>

      <div class="card-body">
        <%= render "form", poet: @poet %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>