config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :friend_requests

      resources :likes

      resources :comments

      resources :poets

      resources :poems
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "poems#index"
  resources :friend_requests
  resources :likes
  resources :comments
  resources :poets
  resources :poems
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  # Direct associations

  belongs_to :poet,
             foreign_key: "liker_id"

  belongs_to :poem

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    poem.to_s
  end
end

app/controllers/api/v1/likes_controller.rb
class Api::V1::LikesController < Api::V1::GraphitiController
  def index
    likes = LikeResource.all(params)
    respond_with(likes)
  end

  def show
    like = LikeResource.find(params)
    respond_with(like)
  end

  def create
    like = LikeResource.build(params)

    if like.save
      render jsonapi: like, status: :created
    else
      render jsonapi_errors: like
    end
  end

  def update
    like = LikeResource.find(params)

    if like.update_attributes
      render jsonapi: like
    else
      render jsonapi_errors: like
    end
  end

  def destroy
    like = LikeResource.find(params)

    if like.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: like
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: %i[show edit update destroy]

  def index
    @q = Like.ransack(params[:q])
    @likes = @q.result(distinct: true).includes(:poem,
                                                :poet).page(params[:page]).per(10)
  end

  def show; end

  def new
    @like = Like.new
  end

  def edit; end

  def create
    @like = Like.new(like_params)

    if @like.save
      message = "Like was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @like, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @like.update(like_params)
      redirect_to @like, notice: "Like was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @like.destroy
    message = "Like was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to likes_url, notice: message
    end
  end

  private

  def set_like
    @like = Like.find(params[:id])
  end

  def like_params
    params.require(:like).permit(:poem_id, :liker_id)
  end
end

app/views/likes/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Like #<%= like.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Poem</dt>
      <dd>
        <% if @like.poem.present? %>
          <%= link_to like.poem, like.poem %>
        <% end %>
      </dd>

      <dt>Liker</dt>
      <dd>
        <% if @like.poet.present? %>
          <%= link_to like.poet, like.poet %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back like, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_like_url(like), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to like, method: :delete, data: { confirm: "Do you really want to delete this like?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(like.updated_at) %> ago
  </div>
</div>

app/views/likes/_form.html.erb
<% was_validated = like.errors.any? %>

<%= form_with(model: like, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% poem_class = "form-control" %>
    <% poem_was_invalid = like.errors.include?(:poem) %>

    <% if was_validated %>
      <% if poem_was_invalid %>
        <% poem_class << " is-invalid" %>
      <% else %>
        <% poem_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :poem_id %>
    <%= f.collection_select :poem_id, Poem.all, :id, :to_s, {}, class: "form-control" %>
    <% if poem_was_invalid %>
      <% like.errors.full_messages_for(:poem).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% liker_class = "form-control" %>
    <% liker_was_invalid = like.errors.include?(:liker) %>

    <% if was_validated %>
      <% if liker_was_invalid %>
        <% liker_class << " is-invalid" %>
      <% else %>
        <% liker_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :liker_id %>
    <%= f.collection_select :liker_id, Poet.all, :id, :to_s, {}, class: "form-control" %>
    <% if liker_was_invalid %>
      <% like.errors.full_messages_for(:liker).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/likes/_likes_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "likes_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :poem_title_cont, "Poem title contains" %>
    <%= f.text_field :poem_title_cont, :class => "form-control", :placeholder => "Poem title contains" %>
  </div>

  <div class="form-group">
    <%= f.label :poet_email_cont, "Poet email contains" %>
    <%= f.text_field :poet_email_cont, :class => "form-control", :placeholder => "Poet email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/likes" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#likes_filters">
  Show filters
</a>

app/views/likes/_list_item.html.erb
<%= link_to like, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= like %>
    <small class="text-muted">
      <%= time_ago_in_words(like.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/likes/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Like #<%= @like.id %>
      </h2>

      <div class="card-body">
        <%= render "form", like: @like %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/likes/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Likes

      <%= link_to new_like_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "likes/likes_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Likes

        <%= link_to new_like_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @likes, partial: "list_item", as: :like %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @likes, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/likes/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Like
      </h2>

      <div class="card-body">
        <%= render "form", like: @like %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/likes/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @like, partial: "card", as: :like %>
  </div>
</div>